[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.fileinfo", "apache"]

[phases.build]
cmds = []

[start]
cmd = "apache2ctl -D FOREGROUND"
